# Generated by Django 2.0.6 on 2020-01-21 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='votes',
        ),
        migrations.AddField(
            model_name='votes',
            name='voted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
