# Generated by Django 2.0.6 on 2020-01-21 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200121_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='voted_by',
        ),
        migrations.AddField(
            model_name='votes',
            name='voted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
