# Generated by Django 2.0.6 on 2020-01-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200124_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='lx',
        ),
        migrations.AddField(
            model_name='history',
            name='lx_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
