# Generated by Django 2.0.6 on 2020-01-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200124_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='lx_id',
            new_name='req_user',
        ),
    ]
