# Generated by Django 2.0.6 on 2020-01-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200124_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_user', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
