# Generated by Django 2.0.6 on 2020-01-30 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_historychat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_id', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('voted_by', models.ManyToManyField(blank=True, related_name='rest_voted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
