"""
Django settings for hu-bot project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!+%c5@@drukjzggd2*#7k^z(rj(do+j5166)kina48r19$%cse'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hu-bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates', 'app')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hu-bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

TWILIO_ACCOUNT_SID = 'AC7e92f8192da472b6b6667d323a91c02a'
TWILIO_API_KEY = '3904e4d4a96c92bf6f6ea005753f4bc7'
TWILIO_API_SECRET = 'FZPdoXjMwIYWuR24hsmRv0MpiwUXBdpL'
TWILIO_CHAT_SERVICE_SID = 'SK4bb28bfdeae796fdb8127a91f21c35c9'
TWILIO_CHAT_SERVICE_SID = 'IS6c96019d20fb4f8b982d96098dce3027'

FB_PAGE_TOKEN = 'EAAHWB3Yp1VoBANdRSVRbZBUj15dYLQtHHZBrr7g9sTghA14ZCeZCmq1ZCcVMnlmdpKnHf8MClHGI1ZBn8SA8l6gZCzRwhB7pUPV5rnLuXGp06bIBxWGoRa2ZCu7I0fvob0MdPvnDPnC4ygJy4URbPmMsOP6rVTY0qfeS6AxorymxQxDWfSEVU7Dz'
# HU_BOT_FB_PAGE_TOKEN = 'EAAHWB3Yp1VoBALtyRvtBN5L9pbBLmIDUKuW0FJo63hbltmKkjp0ddOgnu2QYn03wDpBro94Qqvu1pxavdPa4lIm1Ujiu87vl6JBADHESI69m3N7XZBdp0e9N4uELVuYUvEUkpYTSGNVUsv5xUZCitCzZCUwQIHZBnDbnUPyXUX2CnDd9NU6J'

AUTH_USER_MODEL = 'app.MyUser'

URL = 'https://e24d224f.ngrok.io'